<?php

/**
 * PlugingnWikiPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7264 2010-03-01 21:58:09Z jwage $
 */
abstract class PlugingnWikiPage extends BasegnWikiPage
{

}